name: Receive documentation update trigger
# Receives a trigger from Constellation repository to update documentation.

on: [repository_dispatch, workflow_dispatch]

jobs:
  rebuild-documentation:
    runs-on: ubuntu-latest
    container:
      image: docker://pandoc/latex:2.9
      options: --entrypoint=bash
    permissions:
      contents: write
    steps:
      - name: get actions tools
        run: |
          apk update && apk add --no-cache coreutils && apk add bash && apk add git
      - name: Checkout GitHub Pages repository
        uses: actions/checkout@v3
        with:
          path: pages
      - name: Checkout Constellation repository
        uses: actions/checkout@v3
        with:
          repository: constellation-app/constellation
          path: ./constellation
          ref: documentation_update
      - name: Checkout Constellation-Adaptors repository
        uses: actions/checkout@v3
        with:
          repository: constellation-app/constellation-adaptors
          path: ./constellation-adaptors
          ref: documentation_update
      - name: Checkout constellation_cyber_plugins repository
        uses: actions/checkout@v3
        with:
          repository: AustralianCyberSecurityCentre/constellation_cyber_plugins
          path: ./constellation_cyber_plugins
      - name: remove old pages and make a new directory
        run: |
              rm -rf ./pages/docs/help && mkdir -p ./pages/docs/help
      - name: add execute priveledge and run convert_doc_files.sh
        run: |
              chmod +x ./pages/.github/workflows/convert_doc_files.sh && ./pages/.github/workflows/convert_doc_files.sh
      - name: Auto Commit Documentation Updates
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: 'pages'
          commit_message: 'Documentation Update Automated'
          skip_fetch: true
          commit_options: '--no-verify'
          add_options: '.'
